//! SPEC Protocol napi-rs SDK
//!
//! 将 spec_core 合规引擎的核心 API 暴露给 TypeScript / CAD 插件消费。
//!
//! ## 构建
//! ```bash
//! # 安装 napi-rs CLI
//! npm install -g @napi-rs/cli
//!
//! # 构建 .node 原生模块
//! napi build --release
//!
//! # 产物: spec-sdk.<platform>.node
//! ```
//!
//! ## TypeScript 用法
//! ```typescript
//! import { checkCompliance, discoverReviewPoints, loadRules } from 'spec-sdk';
//!
//! const report = JSON.parse(
//!   checkCompliance(rulesYaml, paramsJson, contextJson)
//! );
//! ```

use napi_derive::napi;
use spec_core::{
    ComplianceEngine, DesignContext, DiscoveryEngine, ParameterTable,
    RuleLibrary, ReviewPointRegistry,
};
use std::path::PathBuf;

/// 合规校核：输入规则 YAML + 参数表 JSON，输出合规报告 JSON。
///
/// - `rules_yaml`: GB150 规则集（YAML 字符串，`- id: ...` 列表）
/// - `params_json`: 参数表（JSON 字符串，含 parameters/limits/attrs）
/// - `context_json`: 可选的 DesignContext（JSON 字符串，含 element_id/element_type/standard）
///
/// 返回: ComplianceReport 的 JSON 字符串
#[napi]
pub fn check_compliance(
    rules_yaml: String,
    params_json: String,
    context_json: Option<String>,
) -> Result<String, String> {
    let engine = ComplianceEngine::from_yaml(&rules_yaml)
        .map_err(|e| format!("规则 YAML 解析失败: {}", e))?;

    let table: ParameterTable = serde_json::from_str(&params_json)
        .map_err(|e| format!("参数表 JSON 解析失败: {}", e))?;

    let context: DesignContext = match context_json {
        Some(json) => serde_json::from_str(&json)
            .map_err(|e| format!("DesignContext JSON 解析失败: {}", e))?,
        None => DesignContext::default(),
    };

    let report = engine.check(&table, context);
    serde_json::to_string_pretty(&report)
        .map_err(|e| format!("报告序列化失败: {}", e))
}

/// 审查点发现：输入参数表 JSON + 规则 YAML，返回候选审查点列表 JSON。
///
/// - `params_json`: 参数表（JSON 字符串）
/// - `rules_yaml`: 规则集（YAML 字符串）
///
/// 返回: Vec<CandidateReviewPoint> 的 JSON 字符串
#[napi]
pub fn discover_review_points(
    params_json: String,
    rules_yaml: String,
) -> Result<String, String> {
    let lib = RuleLibrary::from_yaml(&rules_yaml)
        .map_err(|e| format!("规则 YAML 解析失败: {}", e))?;

    let table: ParameterTable = serde_json::from_str(&params_json)
        .map_err(|e| format!("参数表 JSON 解析失败: {}", e))?;

    let registry = ReviewPointRegistry::default();
    let engine = DiscoveryEngine::new(
        lib,
        registry,
        PathBuf::from("registry.json"),
        PathBuf::from("confirmed"),
    );

    let candidates = engine.discover(&table);
    serde_json::to_string_pretty(&candidates)
        .map_err(|e| format!("候选列表序列化失败: {}", e))
}

/// 加载规则集并返回规则数量。
///
/// - `rules_yaml`: 规则集（YAML 字符串）
///
/// 返回: 规则数量
#[napi]
pub fn load_rules(rules_yaml: String) -> Result<i32, String> {
    let rules: Vec<spec_schema::SpecRule> = serde_yaml::from_str(&rules_yaml)
        .map_err(|e| format!("规则 YAML 解析失败: {}", e))?;
    Ok(rules.len() as i32)
}

/// 增量发现：仅返回与变更条款相关的候选审查点。
///
/// - `params_json`: 参数表（JSON 字符串）
/// - `rules_yaml`: 规则集（YAML 字符串）
/// - `changed_clauses`: 变更条款号列表（JSON 字符串数组，如 `["5.3", "7.3"]`）
///
/// 返回: 过滤后的候选审查点列表 JSON
#[napi]
pub fn discover_changed(
    params_json: String,
    rules_yaml: String,
    changed_clauses_json: String,
) -> Result<String, String> {
    let lib = RuleLibrary::from_yaml(&rules_yaml)
        .map_err(|e| format!("规则 YAML 解析失败: {}", e))?;

    let table: ParameterTable = serde_json::from_str(&params_json)
        .map_err(|e| format!("参数表 JSON 解析失败: {}", e))?;

    let changed_clauses: Vec<String> = serde_json::from_str(&changed_clauses_json)
        .map_err(|e| format!("变更条款 JSON 解析失败: {}", e))?;

    let registry = ReviewPointRegistry::default();
    let engine = DiscoveryEngine::new(
        lib,
        registry,
        PathBuf::from("registry.json"),
        PathBuf::from("confirmed"),
    );

    let candidates = engine.discover_changed(&table, &changed_clauses);
    serde_json::to_string_pretty(&candidates)
        .map_err(|e| format!("候选列表序列化失败: {}", e))
}

// ── TypeScript 类型定义文件生成 ──────────────────

/// 导出 TypeScript 类型声明文件 (.d.ts) 内容。
///
/// 调用此函数可获取 SDK 的 TypeScript 类型定义，
/// 前端项目可将其写入 `spec-sdk.d.ts` 文件使用。
#[napi]
pub fn generate_type_definitions() -> String {
    r#"// SPEC Protocol SDK — TypeScript 类型声明
// Auto-generated by spec_sdk::generate_type_definitions()

export interface Quantity {
  value: number;
  unit: string;
}

export interface ParameterTable {
  parameters: Record<string, Quantity>;
  limits: Record<string, Quantity>;
  attrs: Record<string, string>;
}

export interface DesignContext {
  element_id?: string;
  element_type?: string;
  standard?: string;
}

export interface Violation {
  rule_id: string;
  clause: string;
  assertion_desc: string;
  actual: number | null;
  expected: number | null;
  unit: string | null;
  deviation: number | null;
}

export interface RuleResult {
  rule_id: string;
  clause: string;
  status: 'pass' | 'fail' | 'not_applicable' | 'skipped';
  severity: 'error' | 'warning' | 'info';
  message: string;
  violations: Violation[];
}

export interface ReportSummary {
  total: number;
  passed: number;
  failed: number;
  not_applicable: number;
  skipped: number;
  errors: number;
  warnings: number;
}

export interface ComplianceReport {
  context: DesignContext;
  results: RuleResult[];
  summary: ReportSummary;
}

export interface CandidateReviewPoint {
  rule: SpecRule;
  match_status: 'applicable' | 'uncertain' | 'no_applicability';
  reason: string;
}

export interface SpecRule {
  id: string;
  clause: string;
  severity: 'error' | 'warning' | 'info';
  applicability?: Assertion;
  assertion: Assertion;
  message?: string;
}

export interface Assertion {
  type: string;
  value: unknown;
}

export function checkCompliance(
  rulesYaml: string,
  paramsJson: string,
  contextJson?: string,
): string;

export function discoverReviewPoints(
  paramsJson: string,
  rulesYaml: string,
): string;

export function discoverChanged(
  paramsJson: string,
  rulesYaml: string,
  changedClausesJson: string,
): string;

export function loadRules(rulesYaml: string): number;

export function generateTypeDefinitions(): string;
"#.to_string()
}
